name: unit-tests
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: microsoft
      - run: mvn verify
      - uses: actions/upload-artifact@v4
        with:
          name: test_data-partition-util
          path: target/site