name: unit-tests
on:
  push:
    branches:
      - master
job:
  unit-test:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft
      - run: mvn verify
      - uses: actions/upload-artifact@v4
        with:
          name: test_data-partition-util
          path: target/site